---
# tasks file for docker

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Docker Engine and Compose plugin
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    state: present

- name: Ensure Docker service is started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ansible user to docker group
  user:
    name: ansible
    groups: docker
    append: yes

- name: Add strikercode user to docker group
  user:
    name: strikercode
    groups: docker
    append: yes
