---
# tasks file for gns3-data

- name: Download megacmd deb package
  get_url:
    url: https://mega.nz/linux/repo/Debian_12/amd64/megacmd-Debian_12_amd64.deb
    dest: /tmp/megacmd.deb
    mode: '0644'

- name: Install megacmd
  apt:
    deb: /tmp/megacmd.deb
    state: present

- name: Check if mega session file exists and has size
  become: true
  become_user: gns3
  stat:
    path: /home/gns3/.megaCmd/session
  register: mega_session_file

- name: Perform mega login if session file is missing or empty
  become: true
  become_user: gns3
  shell: |
    mega-login '{{ gns3_megaupload_username }}' '{{ gns3_megaupload_password }}'
  when: not mega_session_file.stat.exists or mega_session_file.stat.size == 0

- name: Run mega-get for GNS3 projects in background
  become: true
  become_user: gns3
  shell: >
    nohup mega-get snoopy/GNS3/projects /home/gns3/GNS3/projects > /home/gns3/mega-get-projects.log 2>&1 &
  async: 1
  poll: 0

- name: Run mega-get for GNS3 images in background
  become: true
  become_user: gns3
  shell: >
    nohup mega-get snoopy/GNS3/images /home/gns3/GNS3/images > /home/gns3/mega-get-images.log 2>&1 &
  async: 1
  poll: 0
