---
# tasks file for gns3-data

- name: Download megacmd deb package
  get_url:
    url: https://mega.nz/linux/repo/Debian_13/amd64/megacmd_2.2.0-2.1_amd64.deb
    dest: /tmp/megacmd.deb
    mode: '0644'

- name: Install megacmd
  apt:
    deb: /tmp/megacmd.deb
    state: present

- name: Check if mega session file exists and has size
  become: true
  become_user: gns3
  stat:
    path: /home/gns3/.megaCmd/session
  register: mega_session_file

- name: Perform mega login if session file is missing or empty
  become: true
  become_user: gns3
  shell: |
    mega-login '{{ gns3_megaupload_username }}' '{{ gns3_megaupload_password }}'
  when: not mega_session_file.stat.exists or mega_session_file.stat.size == 0

- name: Deploy mega-cmd-server systemd unit
  copy:
    dest: /etc/systemd/system/mega-cmd-server.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Mega CMD Server
      After=network.target

      [Service]
      ExecStart=/usr/bin/mega-cmd-server
      Restart=always
      User=gns3
      Group=gns3
      WorkingDirectory=/home/gns3

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start mega-cmd-server
  systemd:
    name: mega-cmd-server
    enabled: yes
    state: started

- name: Run mega-get for GNS3 images in background
  shell: |
    sudo -u gns3 bash -c 'nohup mega-get snoopy/GNS3/images /home/gns3/GNS3 > /home/gns3/mega-get-images.log 2>&1 &'
  async: 1
  poll: 0
