---
# tasks file for github-runner

- name: Create github-runner user
  user:
    name: github-runner
    shell: /bin/bash
    home: /home/github-runner
    create_home: yes

- name: Get github runner binary app
  get_url:
    url: "https://github.com/actions/runner/releases/download/v2.326.0/actions-runner-linux-x64-2.326.0.tar.gz"
    dest: /tmp/actions-runner-linux-x64-2.326.0.tar.gz
    mode: '0644'

- name: Ensure github runner destination directory exists
  file:
    path: /opt/github-runner
    state: directory

- name: Extract github runner binary app
  unarchive:
    src: /tmp/actions-runner-linux-x64-2.326.0.tar.gz
    dest: /opt/github-runner
    remote_src: yes

- name: Ensure github-runner directory ownership
  file:
    owner: github-runner
    group: github-runner
    path: /opt/github-runner
    state: directory
    recurse: yes

- name: Allow github-runner passwordless sudo
  copy:
    dest: /etc/sudoers.d/github-runner
    owner: root
    group: root
    mode: '0440'
    content: |
      github-runner ALL=(ALL) NOPASSWD:ALL

- name: Check if GitHub runner is already configured
  stat:
    path: /opt/github-runner/.runner
  register: runner_config

- name: Configure github runner
  become: true
  become_user: github-runner
  args:
    chdir: /opt/github-runner
  shell: |
    ./config.sh \
      --url https://github.com/wisecode-org \
      --token {{ github_runner_token }} \
      --work /home/github-runner/_work \
      --name snoopy \
      --labels bare-metal,snoopy \
      --unattended --replace
  when: not runner_config.stat.exists

- name: Create GitHub Actions Runner systemd service
  copy:
    dest: /etc/systemd/system/actions.runner.wisecode-org.snoopy.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=GitHub Actions Runner (wisecode-org.snoopy)
      After=network.target

      [Service]
      ExecStart=/opt/github-runner/runsvc.sh
      User=github-runner
      WorkingDirectory=/opt/github-runner
      KillMode=process
      KillSignal=SIGTERM
      TimeoutStopSec=5min

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Ensure github runner service is running
  systemd:
    name: actions.runner.wisecode-org.snoopy
    state: started
    enabled: yes
