---
# tasks file for netdata

- name: Download Netdata edge repo .deb package
  get_url:
    url: "https://repo.netdata.cloud/repos/repoconfig/debian/trixie/netdata-repo-edge_5-1%2Bdebian13_all.deb"
    dest: "/tmp/netdata-repo-edge.deb"
    mode: '0644'

- name: Install Netdata edge repo .deb package
  apt:
    deb: "/tmp/netdata-repo-edge.deb"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install netdata package
  apt:
    name: netdata
    state: present

- name: Deploy Netdata configuration file
  copy:
    dest: "/etc/netdata/netdata.conf"
    owner: root
    group: root
    mode: '0644'
    content: |
      [web]
              bind to = localhost

      [statsd]
              bind to = udp:localhost tcp:localhost

- name: Ensure netdata service is enabled and running
  systemd:
    name: netdata
    enabled: yes
    state: restarted
