---
# tasks file for netdata

- name: Download Netdata GPG key
  get_url:
    url: https://repository.netdata.cloud/netdatabot.gpg.key
    dest: /usr/share/keyrings/netdata-archive-keyring.gpg
    mode: '0644'

- name: Add Netdata APT repository
  copy:
    dest: /etc/apt/sources.list.d/netdata-edge.sources
    owner: root
    group: root
    mode: '0644'
    content: |
      X-Repolib-Name: Netdata edge repository
      Types: deb
      URIs: http://repository.netdata.cloud/repos/edge/debian/
      Suites: bookworm/
      Signed-By: /usr/share/keyrings/netdata-archive-keyring.gpg
      By-Hash: Yes
      Enabled: Yes

      X-Repolib-Name: Netdata repository configuration repository
      Types: deb
      URIs: http://repository.netdata.cloud/repos/repoconfig/debian/
      Suites: bookworm/
      Signed-By: /usr/share/keyrings/netdata-archive-keyring.gpg
      By-Hash: Yes
      Enabled: Yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install netdata package
  apt:
    name: netdata
    state: present

- name: Deploy Netdata configuration file
  ansible.builtin.copy:
    dest: "/etc/netdata/netdata.conf"
    owner: root
    group: root
    mode: '0644'
    content: |
      [web]
              bind to = 127.0.0.1

      [statsd]
              bind to = udp:localhost tcp:localhost

- name: Ensure netdata service is enabled and running
  systemd:
    name: netdata
    enabled: yes
    state: restarted
